# Generated by Django 2.1.4 on 2018-12-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userid',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
